WebAppTodo/Models/Todo/AddTodoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppTodo.Models.Todo
{
    public class AddTodoViewModel
    {
        [Required]
        public string Text { get; set; }

        [Display(Name = "Date due")]
        public DateTime? DateDue { get; set; }

        [Display(Name = "Labels (seperated by comma)")]
        public string Labels { get; set; }
    }
}

WebAppTodo/Models/Todo/CompletedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppTodo.Models.Todo
{
    public class CompletedViewModel
    {

        public List<TodoViewModel> TodoViewModels { get; set; }

        public CompletedViewModel()
        {
            TodoViewModels = new List<TodoViewModel>();
        }
    }
}

WebAppTodo/Models/Todo/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppTodo.Models.Todo
{
    public class IndexViewModel
    {

        public List<TodoViewModel> TodoViewModels { get; set; }

        public IndexViewModel()
        {
            TodoViewModels = new List<TodoViewModel>();
        }
    }
}

WebAppTodo/Models/Todo/TodoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using WebAppTodo.Core;

namespace WebAppTodo.Models.Todo
{
    public class TodoViewModel
    {

        public Guid Id { get; set; }
        public string Text { get; set; }
        public DateTime? DateDue { get; set; }
        public DateTime? Date_show { get; set; }
        public List<TodoItemLabel> TodoItemLabels { get; set; }
        public bool IsCompleted { get; set; }

        public TodoViewModel(TodoItem todoItem)
        {
            Id = todoItem.Id;
            Text = todoItem.Text;
            DateDue = todoItem.DateDue;

            if(todoItem.DateCompleted is null)
            {
                Date_show = todoItem.DateDue;
            }
            else
            {
                Date_show = todoItem.DateCompleted;
            }

            TodoItemLabels = todoItem.Labels;
            IsCompleted = todoItem.IsCompleted;
        }

        public TodoViewModel()
        {

        }
    }
}

WebAppTodo/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAppTodo.Models.Todo;
using WebAppTodo.Core;
using WebAppTodo.Models;
using System.Diagnostics;

namespace WebAppTodo.Controllers
{

    [Authorize]
    public class TodoController : Controller
    {
        private readonly ITodoRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public TodoController(ITodoRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        // GET: /todo/index
        public async Task<IActionResult> Index()
        {
            var todoItems = await _repository.GetActive(await GetUserId());
            IndexViewModel indexViewModel = new IndexViewModel();

            foreach (var td in todoItems)
            {
                TodoViewModel tdv = new TodoViewModel(td);
                indexViewModel.TodoViewModels.Add(tdv);
            }

            return View(indexViewModel);
        }

        public async Task<IActionResult> Completed()
        {
            var todoItems = await _repository.GetCompleted(await GetUserId());
            CompletedViewModel completedViewModel = new CompletedViewModel();

            foreach (var td in todoItems)
            {
                TodoViewModel tdv = new TodoViewModel(td);
                completedViewModel.TodoViewModels.Add(tdv);
            }

            return View(completedViewModel);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTodoViewModel model)
        {
            if (ModelState.IsValid)
            {
                TodoItem newItem = new TodoItem(model.Text, await GetUserId());
                newItem.DateDue = model.DateDue;

                if (!string.IsNullOrEmpty(model.Labels))
                {
                    var lbls = model.Labels.Split(',').Select(tl => tl.Trim().ToLower());
                    foreach (var label in lbls)
                    {
                        if (label.Equals(""))
                        {
                            continue;
                        }

                        var newlbl = new TodoItemLabel(label);
                        var lbl = _repository.LabelExists(newlbl);
                        if (!newItem.Labels.Contains(lbl))
                        {
                            newItem.Labels.Add(lbl);
                        }
                    }
                }
                _repository.Add(newItem);
                return RedirectToAction("Index");
            }
            return View("Add");
        }

        
        public async Task<IActionResult> MarkAsCompleted(Guid guid)
        {
            _repository.MarkAsCompleted(guid, await GetUserId());
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> RemoveFromCompleted(Guid guid)
        {
            var todo = _repository.Get(guid, await GetUserId());

            todo.DateCompleted = null;  
            _repository.Update(todo, await GetUserId());

            return RedirectToAction("Completed");
        }

        public async Task<Guid> GetUserId()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            return new Guid(user.Id);
        }

    }
}

WebAppTodo/Views/Todo/Add.cshtml
@model WebAppTodo.Models.Todo.AddTodoViewModel

@{
    ViewData["Title"] = "Add a Todo";
}

<h2>@ViewData["Title"]</h2>

<div>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Add" method="post">   
                <hr />
                <div class="form-group">
                    <label asp-for="Text"></label> <input asp-for="Text" class="form-control" />
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateDue"></label> <input asp-for="DateDue" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Labels"></label> <input asp-for="Labels" class="form-control" />
                </div>
                <button type="submit" class="btn btn-default">Add</button>
            </form>
        </div>
    </div>
</div>
<div>
    <br/><br/><a asp-action="Index">Go back</a>
</div>

WebAppTodo/Views/Todo/Completed.cshtml
@model WebAppTodo.Models.Todo.CompletedViewModel

@{
    ViewData["Title"] = "Completed todos";
}

<h2>@ViewData["Title"]</h2>

<a asp-action="Add">Add new todo</a> &emsp; <a asp-action="Index">See active todos</a>
<br />
<br />
<br/>
<div>
    @foreach (var item in Model.TodoViewModels)
    {
        @Html.Partial("_TodoPartial", item)
        <hr />
    }
</div>

WebAppTodo/Views/Todo/Index.cshtml
@model WebAppTodo.Models.Todo.IndexViewModel

@{
    ViewData["Title"] = "Todos";
}

<h2>@ViewData["Title"]</h2>

<a asp-action="Add">Add new todo</a> &emsp; <a asp-action="Completed">See completed todos</a>
<br />
<br />
<br/>
<div>
    @foreach (var item in Model.TodoViewModels)
    {
        @Html.Partial("_TodoPartial", item)
        <hr />
    }
</div>

WebAppTodo/Views/Todo/_todopartial.cshtml
@model WebAppTodo.Models.Todo.TodoViewModel

@{
    string countdown = "";
    string showdate = null;


    if(!Model.IsCompleted && Model.DateDue != null)
    {
        showdate = Model.DateDue.GetValueOrDefault().Date.ToString("D");
        var temp = ((DateTime)Model.DateDue - DateTime.UtcNow).Days;
        if (temp > 0)
        {
            countdown = $"(Za {temp} dana!)";
        }
        else if(temp == 0)
        {
            countdown = $"(Danas!)";

        }
        else {
            countdown = $"(Završio prije {temp} dana!)";
        }
    }
    else if(Model.IsCompleted)
    {
        showdate = Model.Date_show.GetValueOrDefault().Date.ToString("D");
    }

}

<div>
    <b>@Model.Text</b><span class="text-danger"> @countdown</span><br />

    @if (showdate != null)
    {
        @showdate<br />
    }

    @{
        if (Model.TodoItemLabels != null && Model.TodoItemLabels.Count > 0)
        {
            <span>Labels: &nbsp;</span>
            foreach (var label in @Model.TodoItemLabels)
            {
                <span>@label.Value &nbsp;</span>
            }
            <br />
        }
    }

    @if (Model.IsCompleted)
    {
        <a asp-controller="Todo" asp-action="RemoveFromCompleted" asp-route-guid="@Model.Id">Remove from completed</a>
    }
    else if(!Model.IsCompleted)
    {
        <a asp-controller="Todo" asp-action="MarkAsCompleted" asp-route-guid="@Model.Id">Mark as completed</a>
    }
</div>